name: daily
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch: {}
   (opcional) también disparar con push a main
   push:
     branches: [main]

concurrency:
  group: daily-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-daily:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python pipelines/fetch_all.py --mode daily
      - run: python pipelines/features.py
      - run: python models/predict.py
      - run: python serving/select_picks.py
      - run: python serving/parlay_builder.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily_outputs
          path: reports/
      - name: Sync to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE }}
        run: python serving/sync_hf.py
   - name: Notify Telegram (robusto)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          HF_SPACE: ${{ secrets.HF_SPACE }}
        if: ${{ (env.TELEGRAM_BOT_TOKEN != '') && (env.TELEGRAM_CHAT_ID != '') }}
        run: |
          set -e
          echo "Verificando bot y chat…"
          curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe" | sed 's/\"id\":[0-9]\+/\"id\":***masked***/g'
          curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getChat?chat_id=${TELEGRAM_CHAT_ID}" | sed 's/\"id\":[-0-9]\+/\"id\":***masked***/g'
          echo "Enviando mensaje…"
          RES=$(curl -s -w "\n%{http_code}" -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="✅ Picks y Parlay publicados.\nSpace: ${HF_SPACE}")
          BODY=$(echo "$RES" | head -n1)
          CODE=$(echo "$RES" | tail -n1)
          echo "HTTP $CODE: $BODY"
          [ "$CODE" = "200" ] || (echo "::error::Falló el envío a Telegram"; exit 1)
